### ISSUE TITLE
auto-archive tweet URL via GET param, for easy use via buttons, bookmarklets, etc

### ISSUE THREAD

**Issue by autonome** [webrecorder/save-tweet-now#7]
eg `https://webrecorder.github.io/save-tweet-now/?t={tweetURL}`

**Comment by autonome** [comment]
and param to auto-upload to IPFS or not.

**Comment by ikreymer** [comment]
This is already supported (and mentioned in the README ;), ex: https://webrecorder.github.io/save-tweet-now/#url=https%3A%2F%2Ftwitter.com%2Fwebrecorder_io%2Fstatus%2F1720185669316641261&autoupload=1

**Comment by ikreymer** [comment]
Oh, or are you just asking to move it to the query string instead of a hash string? That should be doable, but of course just making a GET request alone won't result in an archive, since its all client side and needs to be loaded in the browser.

**Comment by autonome** [comment]
i even read the readme, but not nearly close enough apparently, headsmack 😭
